/* =============================================
   Solfege PRO - Shared Language Selector (dropdown)
   All pages: ja / en / fr / de / es / it / ko / pt-BR
   Per-page titles are emitted by the language build.

   URL convention (directory-based, since 2026-05-26):
     ja: /                            → src/index.html
         /start-here/                 → src/start-here.html
         /guides/                     → src/guides/index.html
         /guides/foo/                 → src/guides/foo.html
         /practice/training-menu/interval/  → nested
     en: /en/                         → en/index.html
         /en/start-here/
         /en/guides/foo/
     fr: /fr/...
     de: /de/...

   Switching language navigates to the sibling lang URL (full page load).

   Backward compat 1: /foo.html / /foo.en.html etc are still served by
     redirect stubs (auto generated by build), so external inbound links
     keep working. lang-toggle does nothing about those — the stubs
     handle the meta-refresh.
   Backward compat 2: /?lang=X query strings are auto-redirected to the
     new path-based equivalent on page load (covers any old bookmarks /
     search results that didn't get caught by the stub layer).
   ============================================= */
(function() {
    var ALL_LANGS = ['ja', 'en', 'fr', 'de', 'es', 'it', 'ko', 'pt-BR'];
    var LANG_LABEL = { ja: 'JA', en: 'EN', fr: 'FR', de: 'DE', es: 'ES', it: 'IT', ko: 'KO', 'pt-BR': 'PT' };
    var LANG_NAMES = { ja: '日本語', en: 'English', fr: 'Français', de: 'Deutsch', es: 'Español', it: 'Italiano', ko: '한국어', 'pt-BR': 'Português (Brasil)' };
    var APP_STORE_LOCALE = { ja: 'jp', en: 'us', fr: 'fr', de: 'de', es: 'es', it: 'it', ko: 'kr', 'pt-BR': 'br' };
    var APP_STORE_BADGE_LOCALE = { ja: 'ja-jp', en: 'en-us', fr: 'fr-fr', de: 'de-de', es: 'es-es', it: 'it-it', ko: 'ko-kr', 'pt-BR': 'pt-br' };
    var APP_STORE_BADGE_ALT = { ja: 'App Storeからダウンロード', en: 'Download on the App Store', fr: 'Télécharger dans l’App Store', de: 'Laden im App Store', es: 'Descargar en el App Store', it: 'Scarica sull’App Store', ko: 'App Store에서 다운로드', 'pt-BR': 'Baixar na App Store' };
    var URL_PREFIX = { ja: '', en: 'en', fr: 'fr', de: 'de', es: 'es', it: 'it', ko: 'ko', 'pt-BR': 'pt-br' };
    var PREFIX_LANG = { en: 'en', fr: 'fr', de: 'de', es: 'es', it: 'it', ko: 'ko', 'pt-br': 'pt-BR' };
    var declared = Array.prototype.map.call(document.querySelectorAll('link[rel="alternate"][hreflang]'), function(link) {
        return link.getAttribute('hreflang');
    });
    var LANGS = ALL_LANGS.filter(function(lang) { return declared.indexOf(lang) !== -1; });
    if (!LANGS.length) LANGS = ALL_LANGS.slice();

    function isValidLang(l) { return LANGS.indexOf(l) !== -1; }

    /**
     * Inspect a pathname and return { lang, basePath } where basePath
     * is the ja-equivalent path (without the /en, /fr, /de prefix).
     *
     * Examples:
     *   /                              → { lang: 'ja', basePath: '/' }
     *   /guides/foo/                   → { lang: 'ja', basePath: '/guides/foo/' }
     *   /en/                           → { lang: 'en', basePath: '/' }
     *   /en/guides/foo/                → { lang: 'en', basePath: '/guides/foo/' }
     *   /guides/foo/                   → { lang: 'ja', basePath: '/guides/foo/' }
     */
    function parsePath(pathname) {
        var m = pathname.match(/^\/(en|fr|de|es|it|ko|pt-br)(\/.*)?$/);
        if (m) return { lang: PREFIX_LANG[m[1]], basePath: m[2] || '/' };
        return { lang: 'ja', basePath: pathname };
    }

    /**
     * Compose a URL pathname for `targetLang` from a basePath (the ja form).
     */
    function pathForLang(basePath, targetLang) {
        if (!basePath || basePath[0] !== '/') basePath = '/' + (basePath || '');
        if (targetLang === 'ja') return basePath;
        // Concatenate /en + /guides/foo/ → /en/guides/foo/
        if (basePath === '/') return '/' + URL_PREFIX[targetLang] + '/';
        return '/' + URL_PREFIX[targetLang] + basePath;
    }

    // -----------------------------------------------------------------
    // Backward compat: rewrite /?lang=X query to the new path-based URL.
    // -----------------------------------------------------------------
    (function maybeRedirectLegacyQuery() {
        var q = new URLSearchParams(window.location.search).get('lang');
        if (!isValidLang(q)) return;
        var parsed = parsePath(window.location.pathname);
        // If already on the requested lang's path, just drop the query.
        if (parsed.lang === q) {
            var u = new URL(window.location.href);
            u.searchParams.delete('lang');
            history.replaceState(null, '', u.toString());
            return;
        }
        // Otherwise navigate to the proper path-based URL.
        try { sessionStorage.setItem('_analytics_redirect_target', q); } catch (e) {}
        var target = pathForLang(parsed.basePath, q);
        var u2 = new URL(window.location.href);
        u2.pathname = target;
        u2.searchParams.delete('lang');
        window.location.replace(u2.toString());
    })();

    var langToggle = document.getElementById('lang-toggle');
    var langText = document.getElementById('lang-text');
    if (!langToggle || !langText) return;

    var pageInfo = parsePath(window.location.pathname);
    var currentLang = pageInfo.lang;
    try { localStorage.setItem('lang', currentLang); } catch (e) {}

    // Chevron
    if (!langToggle.querySelector('.settings-btn__chevron')) {
        var chev = document.createElement('span');
        chev.className = 'settings-btn__chevron';
        chev.setAttribute('aria-hidden', 'true');
        chev.textContent = '▾';
        langToggle.appendChild(chev);
    }

    langToggle.setAttribute('aria-haspopup', 'listbox');
    langToggle.setAttribute('aria-expanded', 'false');
    langToggle.setAttribute('aria-controls', 'lang-menu');
    langToggle.setAttribute('title', 'Select language');

    var menu = document.createElement('ul');
    menu.id = 'lang-menu';
    menu.className = 'lang-menu';
    menu.setAttribute('role', 'listbox');
    menu.setAttribute('aria-label', 'Select language');
    LANGS.forEach(function(l) {
        var li = document.createElement('li');
        var btn = document.createElement('button');
        btn.type = 'button';
        btn.className = 'lang-menu__item';
        btn.setAttribute('data-lang', l);
        btn.setAttribute('role', 'option');
        btn.textContent = LANG_NAMES[l];
        li.appendChild(btn);
        menu.appendChild(li);
    });
    langToggle.parentNode.insertBefore(menu, langToggle.nextSibling);

    function applyMermaidLang(lang) {
        document.querySelectorAll('.mermaid-lang').forEach(function(el) {
            if (el.getAttribute('lang') === lang) el.classList.remove('mermaid-hidden');
            else el.classList.add('mermaid-hidden');
        });
    }

    function updateActiveItem(lang) {
        menu.querySelectorAll('.lang-menu__item').forEach(function(item) {
            var isActive = item.getAttribute('data-lang') === lang;
            item.classList.toggle('is-active', isActive);
            item.setAttribute('aria-selected', isActive ? 'true' : 'false');
        });
    }

    function applyLanguage(lang) {
        document.documentElement.setAttribute('data-lang', lang);
        document.documentElement.lang = lang;
        langText.textContent = LANG_LABEL[lang];
        try { localStorage.setItem('lang', lang); } catch (e) {}
        currentLang = lang;

        var storeLocale = APP_STORE_LOCALE[lang];
        var badgeLocale = APP_STORE_BADGE_LOCALE[lang];
        var badgeAlt = APP_STORE_BADGE_ALT[lang];
        document.querySelectorAll('a[href*="apps.apple.com"]').forEach(function(a) {
            a.href = a.href.replace(/apps\.apple\.com\/[a-z]{2}\//, 'apps.apple.com/' + storeLocale + '/');
            var img = a.querySelector('img.app-store-link__img');
            if (!img) {
                a.textContent = '';
                a.classList.add('app-store-link');
                a.setAttribute('aria-label', badgeAlt);
                img = document.createElement('img');
                img.className = 'app-store-link__img';
                img.loading = 'lazy';
                a.appendChild(img);
            }
            img.src = 'https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/' + badgeLocale;
            img.alt = badgeAlt;
        });

        var ds = document.documentElement.dataset;
        var titleByLang = { ja: ds.titleJa, en: ds.titleEn, fr: ds.titleFr, de: ds.titleDe, es: ds.titleEs, it: ds.titleIt, ko: ds.titleKo, 'pt-BR': ds.titlePtBr };
        if (titleByLang[lang]) document.title = titleByLang[lang];

        applyMermaidLang(lang);
        updateActiveItem(lang);
        window.dispatchEvent(new Event('langchange'));
    }

    /**
     * Rewrite internal absolute links so visiting from /en/foo/ keeps the
     * user inside /en/ when they click another internal link. Skipped for
     * ja (no prefix to add).
     *
     * Only touches links whose pathname starts with /, points to the same
     * origin, and is not an asset (.css/.js/.png/etc.).
     */
    function rewriteInternalLinks(lang) {
        if (lang === 'ja') return;
        var links = document.querySelectorAll('a[href]');
        links.forEach(function(a) {
            var href = a.getAttribute('href');
            if (!href) return;
            // Skip external / mailto / tel / anchor / javascript
            if (/^(mailto:|tel:|javascript:|#)/i.test(href)) return;
            var abs;
            try { abs = new URL(href, window.location.href); }
            catch (e) { return; }
            if (abs.origin !== window.location.origin) return;
            // Skip assets
            if (/\.(png|jpe?g|svg|gif|ico|css|js|pdf|xml|txt|webp)$/i.test(abs.pathname)) return;
            var parsed = parsePath(abs.pathname);
            if (parsed.lang === lang) return; // already correct
            abs.pathname = pathForLang(parsed.basePath, lang);
            a.setAttribute('href', abs.pathname + abs.search + abs.hash);
        });
    }

    function closeMenu() {
        menu.classList.remove('open');
        langToggle.setAttribute('aria-expanded', 'false');
    }
    function openMenu() {
        menu.classList.add('open');
        langToggle.setAttribute('aria-expanded', 'true');
    }

    applyLanguage(currentLang);
    rewriteInternalLinks(currentLang);

    langToggle.addEventListener('click', function(e) {
        e.stopPropagation();
        if (menu.classList.contains('open')) closeMenu();
        else openMenu();
    });

    menu.addEventListener('click', function(e) {
        var item = e.target.closest('.lang-menu__item');
        if (!item) return;
        var lang = item.getAttribute('data-lang');
        if (!isValidLang(lang)) return;
        var current = parsePath(window.location.pathname);
        var target = pathForLang(current.basePath, lang);
        if (target === window.location.pathname) {
            closeMenu();
            return;
        }
        var u = new URL(window.location.href);
        u.pathname = target;
        u.searchParams.delete('lang');
        window.location.href = u.toString();
    });

    document.addEventListener('click', function(e) {
        if (!menu.contains(e.target) && !langToggle.contains(e.target)) closeMenu();
    });
    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape' && menu.classList.contains('open')) {
            closeMenu();
            langToggle.focus();
        }
    });
})();
